apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: zinefodil/auth:1
          imagePullPolicy: IfNotPresent
          name: auth
      restartPolicy: Always