apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - image: zinefodil/gateway:1
          imagePullPolicy: IfNotPresent
          name: gateway
      restartPolicy: Always