apiVersion: v1
kind: Service
metadata:
  name: resources
spec:
  ports:
    - nodePort: 31280
      port: 8002
      protocol: TCP
      targetPort: 8002
  selector:
    app: resources
  type: NodePort