apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resources
  template:
    metadata:
      labels:
        app: resources
    spec:
      containers:
        - image: zinefodil/resources:1
          imagePullPolicy: IfNotPresent
          name: resources
      restartPolicy: Always